---
- hosts: all
  become: true
  pre_tasks:

  -  name: install updates Ubuntu
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"

- hosts: controller
  become: true
  roles:
    - Keystone
    - Glance

- hosts: compute
  become: true
  roles:
    - Nova
